name: Star Notify
on:
  watch:
    types: [started]
jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download Scripts
        run: |
          wget https://raw.githubusercontent.com/foyoux/started-notify/main/.github/workflows/star_notify.py#${{github.run_id}}
      - name: Send Email
        run: |
          python star_notify.py ${{github.token}} ${{secrets.NOTIFY_EMAIL}}
