name: Started Notify
on:
  watch:
    types: [ started ]
jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download Scripts
        run: |
          wget https://raw.githubusercontent.com/foyoux/started-notify/main/.github/workflows/started_notify.py#${{github.run_id}}
      - name: Send Notify Email
        run: |
          python started_notify.py ${{github.token}} ${{secrets.NOTIFY_EMAIL}}
